### ISSUE TITLE
No Contact Email

### ISSUE THREAD

**Issue by tim--c** [mecha-cms/mecha-cms#44]
Hi,

I was unable to find a contact email. Neither security@mecha-cms.com, support@mecha-cms.com, or info@mecha-cms.com seem to exist.

I want to report sensitive issues and would prefer to not do so publicly. 

Regards

**Comment by tovic** [comment]
@tim--c Unfortunately, this project is actually more personal than you think. I decided to made it as an open source code project because I think my idea would be beneficial for many people. Email creation for the **Mecha CMS** site is still not a priority. If you want to inform a particular issue, you can contact me via the contact page on my personal blog, thanks :)

&rarr; http://latitudu.com/contact

**Comment by tim--c** [comment]
Thanks for getting back to be so quickly. Your contact form got me a 404 (I tried with chrome and firefox). Let me know if you got my mail anyways.

**Comment by tovic** [comment]
Use this email: t[dot]nurrohman77[at]gmail[dot]com
